### ISSUE TITLE
BLE Server module resets after I set flash to 4MB and disable external RAM

### ISSUE THREAD

**Issue by freeride01** [chegewara/esp32-OTA-over-BLE#2]
Hi,
I am very interested to try the BLE OTA server & client example. I am using ESP32-PICO-KIT, Eclipse and ESP-IDF 4.0. I flashed the BLE server example to the kit, but first I got a "Failed to init external RAM" error, so I disabled it from SDKconfig, then I got an error "spi_flash: Detected size(4096k) smaller than size in binary image header", so I set flash size to 4MB, again in SDKconfig. (ESP32-PICO-KIT does not have external RAM and has 4MB embedded flash.)
Now I can upload the project without any errors, but when I reach the point where the server has to start downloading from the HTTP server (which I set up on my PC), the module resets with a Guru Meditation Error.

```
Heap summary for capabilities 0x00000400:
  Totals:
    free 0 allocated 0 min_free 0 largest_free_block 0
Guru Meditation Error: Core  1 panic'ed (StoreProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x4000c350  PS      : 0x00060030  A0      : 0x800d8786  A1      : 0x3ffdba70  
A2      : 0x00000000  A3      : 0x3ffd86f0  A4      : 0x00000132  A5      : 0x00000000  
A6      : 0x200206e9  A7      : 0x19242002  A8      : 0x00ee4008  A9      : 0x3ffdba50  
A10     : 0x00000000  A11     : 0x00000002  A12     : 0x000019cc  A13     : 0x3ffd8c14  
A14     : 0x00000001  A15     : 0xfffffffc  SAR     : 0x00000010  EXCCAUSE: 0x0000001d  
EXCVADDR: 0x00000000  LBEG    : 0x4000c349  LEND    : 0x4000c36b  LCOUNT  : 0x00000012  

ELF file SHA256: 23b44664824fe06ca26f5f08465c402e619b62865769cca06eab405b8d294d3f

Backtrace: 0x4000c34d:0x3ffdba70 |<-CORRUPTED
```

Does my module have to have external RAM and 16MB flash for the project to work?

**Comment by chegewara** [comment]
BLE server is downloading and storing binary file in SPIRAM, so you need it:
https://github.com/chegewara/esp32-OTA-over-BLE/blob/master/BLE_server/main/http_client.c#L74

**Comment by freeride01** [comment]
I am now using ESP32-DevKitC with 8MB RAM/8MB flash. The project flashes on chip, but now the association to the AP fails.
Debug output:

```
D (6850) wpa:  00
D (6850) wpa:  f5
D (6850) wpa:  00
D (6860) wpa:  b9
D (6860) wpa:  ea
D (6860) wpa:  02
D (6860) wpa:  9b
D (6860) wpa:  7d
D (6870) wpa:  d6
D (6870) wpa:  b6
D (6870) wpa:  40
D (6870) wpa:  ac
D (6870) wpa:  48
D (6880) wpa:  1b
D (6880) wpa:  19
D (6880) wpa:  f0
D (6880) wpa: 

D (6880) wpa:  36
D (6890) wpa:  00
D (6890) wpa:  16
D (6890) wpa:  30
D (6890) wpa:  14
D (6890) wpa:  01
D (6900) wpa:  00
D (6900) wpa:  00
D (6900) wpa:  0f
D (6900) wpa:  ac
D (6900) wpa:  04
D (6910) wpa:  01
D (6910) wpa:  00
D (6910) wpa:  00
D (6910) wpa:  0f
D (6910) wpa:  ac
D (6920) wpa: 

D (6920) wpa:  04
D (6920) wpa:  01
D (6920) wpa:  00
D (6920) wpa:  00
D (6930) wpa:  0f
D (6930) wpa:  ac
D (6930) wpa:  02
D (6930) wpa:  00
D (6930) wpa:  00
D (6940) wpa: 

D (6950) esp_timer: timer queue overflow
D (6950) esp_timer: timer queue overflow
D (6950) esp_timer: timer queue overflow
I (16090) wifi: state: run -> init (cc00)
```

**Comment by chegewara** [comment]
You should check with simple AP example and then try to work with wifi settings in menuconfig.

**Comment by freeride01** [comment]
I ran native_ota_example on the ESP-PICO-KIT with no problems, but not on the ESP32-DevKitC. I'll try it.

**Comment by freeride01** [comment]
After downloading IDF 4.2.2, I managed to get Simple OTA Example to work, but not the BLE Server. It still starts connecting and then disconnects from the AP.
The only difference in the  WiFi config seems to be _Type of WiFi TX buffers_ - set to _Dynamic_ in Simple OTA Example, but in BLE Server there is only the _Static_ option.

**Comment by chegewara** [comment]
I really dont know why you can have issue with AP.
I made this code as example long time ago and not supporting or testing it anymore.

**Comment by freeride01** [comment]
I understand.
I got it working. One last question: is the firmware version read from version.txt? Because after downloading the new image, it doesn't update the firmware. It says "Firmware already installed", even though I changed the version in version.txt.

**Comment by chegewara** [comment]
Yes, but for ota update it also checks internal version and SHA. You cant update with exactly the same binary.

**Comment by freeride01** [comment]
OK, thank you.
